sudo: required
language: generic 

services:
  - docker

before_install:
  - docker build -t olivierod65/docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true olivierod65/docker-react npm run test
